### ISSUE TITLE
definition of dfile, delt, time...

### ISSUE THREAD

**Issue by auroralin0408** [Mesharou/Pyticles#2]
I am currently using Pyticles to do backward tracking, but encountered some difficulities in understanding the code.

Assume that I have 3 output files from ROMS with each file containing 10 days of hourly output data, and I want hourly Pyticles output. **So the `delt=3600`in seconds, right?** and it's supposed to set
```
dfile = -1/240
start_file = 3
end_file = 1
```
but `timerange = np.round(np.arange(start_file, end_file + dfile, dfile),3)`,  **will it decrease the accuracy of time resolution?**

for each loop(`for time in timerange:`), it seems to use `prev_time = np.ceil(time); next_time = np.floor(time)` to update velocity, and the `ocean_time` wrote in the Pyticles output file is not corresponding to ROMS output, which made me quite confused. Can anyone help to elucidate this?

Looking forward to any kind reply :)

**Comment by Mesharou** [comment]
In fact, "start_file, end_dile and dfile" correspond to ROMS model time steps (as defined in simul.dt), so 0 is the first output data (ocean_time=ocean_time_0), 1 would be the next available time step (ocean_time=ocean_time_0 + simul.dt), etc. So in your case you should define:

dfile = -1
start_file = 1019
end_file = 0

The actual number of output files does not matter for these values. 

However, the structure of your output files must be defined in Modules/R_files.py. And for your simulation you need to define that each file contains 240 time steps (10 days of hourly files) by specifying the value of "tfile" as 240:

  if 'my_croco_simul' in simul:
    ...
    self.tfile = 240

The simul.dt is automatically defined by reading ocean_time in two successive outputs.

Some further documentation (under construction) can be found here: https://github.com/Mesharou/Pyticles/blob/tutorials/Docs/running-pyticles.md

**Comment by auroralin0408** [comment]
Thanks for your quick reply! It helps me a lot, but I want to confirm one more thing:

No matter how many ROMS output files I have, just assume it has 24000 timesteps in total. So `self.tfile = 240; self.tstart = 0;  self.tend = 24000`? And if I want to do backward tracking in a certain period, just to set `dfile = -1; start_file = 1019; end_file = 48`?

**Comment by Mesharou** [comment]
This looks right. Actually, the tend parameter is not used anywhere in the code. But yes, start_file would be the index of the first time-step you want to use, and end_file would be the last one (with end_file smaller than start_file if dfile is negative).

**Comment by auroralin0408** [comment]
Got that, thanks!

**Comment by auroralin0408** [comment]
Hi mesharou, I tried to run but it failed. I've set `self.tfile = 240.  dfile = -1 ;start_file = 528 ; end_file = 360 `, and the ROMS output files are 00001,00002...00006.nc. But it tends to find 00480.nc at the first beginning?
<img width="450" alt="image" src="https://github.com/user-attachments/assets/822d40a4-2cee-444a-b2dc-b39d6b7c63dd">
what's wrong here?

**Comment by Mesharou** [comment]
By default the code assumes that the files are called:
ocean_his_00000.nc
ocean_his_00240.nc
ocean_his_00480.nc
etc.

If it is not the case, but files use numbering 00000.nc, 00001.nc, 00002.nc, instead you can modify the following line:

self.filetime=self.time-self.infiletime

into 

self.filetime=self.time//self.ncname.tfile

(beware you have to modify the line twice, in "__init__" and in "update").

**Comment by auroralin0408** [comment]
I modified as you said and it ran successfully, THANKS!
